version: '3'

services:
  bcc-trial:
    build: .
    container_name: bcc-trial
    volumes:
      - /sys/kernel/debug:/sys/kernel/debug:rw
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
      - /etc/localtime:/etc/localtime:ro
      - ./src:/app
    working_dir: /usr/share/bcc/tools
    privileged: true
    tty: true
#    command: >
#      /usr/bin/python3 /app/main.py